fix(modal): check if event exist before accessing, give ellipsis width
sebgroup/react-components pull request #467
Opened 2020-09-09 09:15 UTC by DanSallau

2020-09-09 09:52 UTC, omarVodiaK approved these changes

2020-09-09 09:53 UTC, mario-subo approved these changes

2020-09-10 02:21 UTC, yousifalraheem requested changes

2020-09-10 02:21 UTC, yousifalraheem commented on src/Modal/Modal.tsx
> +            if (e?.key?.toLowerCase() === "escape" && escapeToDismiss) {
I don't think you need to check if the event exist. It will always exist, if not, there is an issue either in the browser or in React itself

2020-09-10 08:50 UTC, merged

2020-09-22 02:27 UTC, yousifalraheem commented
:tada: This PR is included in version 4.5.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@sebgroup/react-components/v/4.5.1)
- [GitHub release](https://github.com/sebgroup/react-components/releases/tag/v4.5.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: